### PR TITLE
fix: Removing securitycontrols.md and security control tags from experimentation

### PR DESCRIPTION
**Pull request by johnswayty-ssc**
Ran into an issue with the last PR kindly review this one. Apologies.

### CODE REVIEW

**Review by fmichaelobrien — APPROVED** [review]
/lgtm

**Review by tackaberry — APPROVED** [review]

**Review by alaincormier-ssc — APPROVED** [review]
lgtm

reminder if we want to bump the release tags, to add "`fix:`" in the PR/commit title before merging

**Review by lucstjean-ssc — APPROVED** [review]
/lgtm

**Review by alaincormier-ssc — APPROVED** [review]

**Review by tackaberry — APPROVED** [review]
lgtm

**Pull request merged**
