### PR TITLE
Updated README Docs

### PR DESCRIPTION
**Pull request by cartyc**
Updated some gaps in the LZ Readme docs.
- Added commands to enable cloudbilling and accesscontext management APIs in the management project
- Updated rootsync name and Kubernetes Service Account References
- Renamed landing-zone artifact name.
- Updated missing `${}` around some PROJECT_ID var calls.

### CODE REVIEW

**Comment by cartyc** [comment]
Closing in favor of #191

**Review by fmichaelobrien — APPROVED** [review]
/lgtm

**Comment by obriensystems** [comment]
verified SA account permissions ok on ACM
```
  echo "Enabling APIs"
  gcloud services enable krmapihosting.googleapis.com 
  gcloud services enable container.googleapis.com
  #compute.googleapis.com
  gcloud services enable cloudresourcemanager.googleapis.com 
  gcloud services enable accesscontextmanager.googleapis.com 
  gcloud services enable cloudbilling.googleapis.com
```

```
michael@cloudshell:~/dev/pdt-oldev/obriensystems (kcc-lz-8597)$ kubectl get gcp | grep UpToDate 
accesscontextmanageraccesslevel.accesscontextmanager.cnrm.cloud.google.com/commonaccesslevels        64m   True    UpToDate   64m
accesscontextmanageraccesslevel.accesscontextmanager.cnrm.cloud.google.com/nonprodperimaccesslevel   64m   True    UpToDate   64m
accesscontextmanageraccesslevel.accesscontextmanager.cnrm.cloud.google.com/prodaccesslevels          64m   True    UpToDate   64m
```
Screen Shot 2022-12-07 at 21 10 37

**Comment by fmichaelobrien** [comment]
LGTM
Already reviewed previously - and in our discussion
We need these changes - thanks Chris

**Pull request merged**
