### PR TITLE
feat: remove yakima roles from bootstrap

### LINKED ISSUE #286: landing-zone-v2: remove granted permissions for config-control from bootstrap
it would be better to grant just the minimum number of permissions to the config-control namespace through the bootstrap process and manage any extra permissions with a config-connector resource

### PR DESCRIPTION
**Pull request by stephanemillaire-ssc**
Closes #286 

- adds the two required roles for the yakima service account being removed in the bootstrap to namespaces/management-namespace.yaml
- updates bootstrap documentation to reflect above change
- updates documentation to rename uat to preprod

### CODE REVIEW

**Review by lucstjean-ssc — APPROVED** [review]
/lgtm Good work!

**Review by alaincormier-ssc — APPROVED** [review]
nice work!

**Review by ovidiuasiminei-ssc — APPROVED** [review]
Great work !

**Review by cartyc — APPROVED** [review]
thanks Stephane!

/lgtm

**Review by fmichaelobrien — APPROVED** [review]
LGTM
- preprod diagram updates good

**Pull request merged**
