### PR TITLE
Yaml linting

### PR DESCRIPTION
**Pull request by KingBain**
Start that conversation linting in the repo, as well as YAML coding standard. This PR is strictly focused on YAML files, but I think getting this set. The next logical linting step would be for kube based YML files ...using something like kudeconform.

### CODE REVIEW

**Comment by KingBain** [comment]
I wouldnt merge this yet as some of the in place yml files need to be updated

**Comment by cartyc** [comment]
Hey @KingBain excellent idea! Currently we're using both `nomo` and the `kubeval` plugin for `kpt` but any additional linting improvement we can make is more than welcome :)

**Review by KingBain — COMMENTED** [review]
@cartyc this wouldnt normally be caught by linting, but is there a yaml parser we could use to verify yaml syntax before merge ? 

https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/pull/275/commits/4bb39c39dd9a22873207a33dbad17fc5d86d07b2

**Comment by KingBain** [comment]
Since the code base in basically in place I changed the line length error to just a warning. 
Its not a deal breaker, but some lines are 300 characters long and a lot of the license text is over 80 characters

**Comment by fmichaelobrien** [comment]
reviewing over the next 24-48h

**Comment by KingBain** [comment]
Resolved merge conflicts
Updated files for linting

**Review by fmichaelobrien — DISMISSED** [review]
LGTM

**Review by fmichaelobrien — APPROVED** [review]
LGTM

**Review by DaveStunTueur — COMMENTED** [review]
@alaincormier-ssc is working on a linting story so we should wait on his input on this PR before proceeding. thank you

**Review by DaveStunTueur — CHANGES_REQUESTED** [review]
@alaincormier-ssc is working on a linting story so we should wait on his input on this PR before proceeding. thank you

**Comment by KingBain** [comment]
👍

**Pull request closed without merging**
