### PR TITLE
fix: adding security control tags

### LINKED ISSUE #804: docs: security controls tagging
general issue to track upcoming security controls tagging PRs

### PR DESCRIPTION
**Pull request by davelanglois-ssc**
Adding security control tags to the following packages:
- client-landing-zone
- core-landing-zone
- gke/configconnector/gke-admin-proxy
- gke/configconnector/gke-cluster-autopilot
- gke/configconnector/gke-defaults
- gke/kubernetes/cluster-defaults
- ids

closes #804

### CODE REVIEW

**Review by alaincormier-ssc — APPROVED** [review]
lgtm

**Review by fmichaelobrien — APPROVED** [review]
/lgtm

Thanks Dave, also reviewing the pythin change

**Review by tackaberry — DISMISSED** [review]

**Comment by davelanglois-ssc** [comment]
don't merge yet, additionnal tags need to be added

**Comment by davelanglois-ssc** [comment]
> don't merge yet, additionnal tags need to be added

It's now READY. all tags have been added

**Review by fmichaelobrien — APPROVED** [review]
AC, SI, SC changes look good
/lgtm

**Review by alaincormier-ssc — APPROVED** [review]

**Pull request merged**
