### PR TITLE
feat: adding an example for a tier3 SSL policy

### PR DESCRIPTION
**Pull request by davelanglois-ssc**
this example provide guidance on how to create an SSL policy that uses CCCS approved ciphers

### CODE REVIEW

**Comment by cartyc** [comment]
Wanted to add this issue from the Tracker app for reference. 
https://github.com/canada-ca/tracker/pull/3828

**Review by alaincormier-ssc — APPROVED** [review]

**Review by fmichaelobrien — APPROVED** [review]
LGTM
thanks Dave and team

**Comment by cartyc** [comment]
@KingBain @sleepycat fyi

**Review by lucstjean-ssc — APPROVED** [review]
/lgtm

**Pull request merged**
