### PR TITLE
fix: Move legacy packages into Legacy Dir

### PR DESCRIPTION
**Pull request by cartyc**
This PR moves a number of legacy packages into a `legacy` directory. The intent is to allow these packages to still be consumed by users who may already be using them and decrease confusion about which packages should be used.

Packages moved
- `hierarchy`
- `landing-zone`
- `landing-zone-v2`
- `logging`
- `org-policies`

If you are using one of these packages you can update the `kptfile` to target `solutions/legacy/<package-name>` instead of the existing `solutions/<package-name>` path.

### CODE REVIEW

**Comment by cartyc** [comment]
Need to rebase, pushed from `constrains-update` branch by accident.

**Comment by cartyc** [comment]
Fix force pushed

**Review by fmichaelobrien — APPROVED** [review]
LGTM
as discussed in one of our meets - this is a good PR to partition older V1 and V2 packages including landing-zone-v2 which is replaced by the two core-landing-zone folders

**Review by alaincormier-ssc — APPROVED** [review]
lgtm

**Pull request merged**
