### PR TITLE
fix: IAM partial policy logSinkRef updated to mgmt-project

### PR DESCRIPTION
**Pull request by Michael-McAuley-SSC**

### CODE REVIEW

**Comment by Michael-McAuley-SSC** [comment]
Fixes issue with the log sink writer permissions not matching the the log sink name.

**Comment by Michael-McAuley-SSC** [comment]
Found issue with kptfile, will have more commits

**Review by fmichaelobrien — COMMENTED** [review]
LGTM
Nice

**Review by fmichaelobrien — APPROVED** [review]
LGTM

**Pull request merged**
