### PR TITLE
fixed nonprod firewall

### PR DESCRIPTION
**Pull request by davelanglois-ssc**
consistent with terraform LZ

### CODE REVIEW

**Comment by davelanglois-ssc** [comment]
I have fixed my cla

**Review by cartyc — APPROVED** [review]
/lgtm

**Comment by fmichaelobrien** [comment]
related 
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/issues/158

aligns with
https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/blob/main/environments/nonprod/nonp-firewall.auto.tfvars#L46

**Comment by fmichaelobrien** [comment]
closes https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/issues/75

**Pull request merged**
