### PR TITLE
#568 - make GKE Yakima SA roles clearer

### PR DESCRIPTION
**Pull request by fmichaelobrien**
Take out the indenting that makes it look like yakima roles are only on GKE standard
See #568 
Some developers that are not running setup-kcc.sh are missing the role - causing core-landing-zone not to deploy
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/wiki/DevOps#continue-kpt-fn-render-after-failed-services-fixed

### CODE REVIEW

**Comment by fmichaelobrien** [comment]
Weird, we may need to resign our CLA after 2 years
fmichaelobrien	94715080+fmichaelobrien@users.noreply.github.com	Need CLA

**Review by cartyc — APPROVED** [review]

**Comment by cartyc** [comment]
Thanks Mike! Much clearer now, hopefully this reduces the times the credentials step gets skipped over.

**Review by alaincormier-ssc — APPROVED** [review]

**Comment by fmichaelobrien** [comment]
Let me know if anyone else has any comments on this change.  I will to the next one under #603

**Comment by fmichaelobrien** [comment]
Added to COA
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/wiki/Contributor-Onboarding-Agreement#coa-2-pull-request-recommendations

**Pull request merged**
